threatIntelligence/androguard/urls.py
from django.conf.urls import url
from . import views

app_name = 'androguard'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

threatIntelligence/machineLearning/urls.py
from django.conf.urls import url
from . import views

app_name = 'machineLearning'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

threatIntelligence/threatIntelligence/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from mobileappanalysis import urls as mobileappanalysisURLS
from machineLearning import urls as machineLearningURLS
from vtkoodousscraper import urls as vtkoodousscraperURLS
from androguard import urls as androguardURLS
import views

urlpatterns = [
    url(r'^$', views.index, name='mainIndex'),
    url(r'^admin/', admin.site.urls),
    url(r'^apk/', include(mobileappanalysisURLS)),
    url(r'^ml/', include(machineLearningURLS)),   
    url(r'^scraper/', include(vtkoodousscraperURLS)),
    url(r'^androguard', include(androguardURLS))
]

threatIntelligence/machineLearning/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.postgres.fields import ArrayField
from mobileappanalysis.models import apk as apkmodel

# Create your models here.

class flat_app_features(models.Model):
    apk = models.ForeignKey(apkmodel, on_delete=models.CASCADE,null=True)
    category =  models.TextField()
    feature = models.TextField()
    
    def __str__(self):
        return "%s , %s , %s " % (self.apk , self.feature , self.category)


class observed_features(models.Model):
    category =  models.TextField()
    feature = models.TextField()
    
    def __str__(self):
        return "%s , %s " % (self.feature , self.category)


class vector_app_features(models.Model):
    apk = models.ForeignKey(apkmodel, on_delete=models.CASCADE,null=True)
    bag = ArrayField(models.TextField())
    vector = ArrayField(models.IntegerField())
    
    def __str__(self):
        return "%s" % (self.apk)

threatIntelligence/machineLearning/views.py
from django.shortcuts import render


def index(request):
    response = {}
    if request.method =="GET":
        return render(request, 'machineLearning/index.html', response)
    # else:
    #     if 'calculate' in request.POST.keys():
    #         truncate_mldata()
    #         generate_feature_reps()
    #     else:
    #         ml_main()
    
    return render(request, 'machineLearning/index.html', response)

threatIntelligence/machineLearning/templates/machineLearning/index.html
{% load static %}
<html>
<head>
	<title>Machine Learning Index</title>
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
</head>
<body>
	<center>
		<h1>
			Machine Learning Index
		</h1>
		<div id="main">
			<form method="POST" action="{% url 'machineLearning:index' %}">
			{% csrf_token %}
<!--				<h2>Breakdown of observed features</h2>-->
        <p>This page currently does nothing. Models are trained offline.</p>
<!--
				<p>Creates observed_features_table and displays a breakdown of the count by category.</p>
				<input type="submit" name="calculate" value="Calculate"><br>
				{% if error %}
					<h3 colour="red">{{ error }}</h3>
				{% endif %}
        <br>
        <table>
        <tr>
          <th>Total</th>
          <th>{{featurecount}}</th>
        </tr>
        <tr>
          <td>Class</td>
          <td>{{classcount}}</td>
        </tr>
        <tr>
          <td>Component</td>
          <td>{{componentcount}}</td>
        </tr>
        <tr>
          <td>Intent</td>
          <td>{{intentcount}}</td>
        </tr>
        <tr>
          <td>Method</td>
          <td>{{methodcount}}</td>
        </tr>
        <tr>
          <td>Permission</td>
          <td>{{permissioncount}}</td>
        </tr>
        <tr>
          <td>URL</td>
          <td>{{urlcount}}</td>
        </tr>
    </table>
-->
<!--
        <h2>Train classifiers</h2>
				<p>Trains some simple classifiers and reports their accuracy on the apps in the database.
          <br>Displays highly weighted features that are determined to be important for distinguishing malware by the classifiers.</p>
				<input type="submit" name="train" value="Train">
				{% if error %}
					<h3 colour="red">{{ error }}</h3>
				{% endif %}
-->
<!--
        <h2>Predict if malware</h2>
				<p>Please insert an apk file to predict if it is malware.</p>
				<textarea rows="4" cols="50" name="hashes"></textarea>
-->
			</form>
		</div>

	</center>
</body>
</html>