threatIntelligence/androguard/urls.py
from django.conf.urls import url
from . import views

app_name = 'androguard'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

threatIntelligence/mobileappanalysis/urls.py
from django.conf.urls import url
from . import views

app_name = 'mobileappanalysis'

urlpatterns = [
    url(r'^$', views.index, name="index"),
]

threatIntelligence/threatIntelligence/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from mobileappanalysis import urls as mobileappanalysisURLS
from machineLearning import urls as machineLearningURLS
from vtkoodousscraper import urls as vtkoodousscraperURLS
from androguard import urls as androguardURLS
import views

urlpatterns = [
    url(r'^$', views.index, name='mainIndex'),
    url(r'^admin/', admin.site.urls),
    url(r'^apk/', include(mobileappanalysisURLS)),
    url(r'^ml/', include(machineLearningURLS)),   
    url(r'^scraper/', include(vtkoodousscraperURLS)),
    url(r'^androguard', include(androguardURLS))
]

threatIntelligence/mobileappanalysis/models.py
from __future__ import unicode_literals
from django.contrib.postgres.fields import JSONField, ArrayField
from django.utils.encoding import python_2_unicode_compatible
from django.db import models

# Create your models here.
@python_2_unicode_compatible
class virustotal(models.Model):
    sha256sum = models.CharField(max_length=64,unique=True)
    detected = models.IntegerField()
    total = models.IntegerField()
    permalink = models.URLField(max_length=500,default=None,unique=True)
    sophos_tag = models.CharField(max_length=200)
    json_analysis = JSONField(default=None,unique=True)
    
    def __str__(self):
        return "%s , %s , %s , %s , %s" % (self.detected  , self.total  , self.permalink  , self.sophos_tag  , self.json_analysis)

@python_2_unicode_compatible
class koodous(models.Model):
	sha256sum = models.CharField(max_length=64,unique=True)
	rating = models.CharField(max_length=64,null=True)
	tags = models.CharField(max_length=500)
	json_analysis_initial = JSONField()
	json_analysis_detailed = JSONField()

	def __str__(self):
		return "%s , %s" % (self.tags , self.json_analysis)

@python_2_unicode_compatible
class apk(models.Model):
	md5sum = models.CharField(max_length=32,unique=True)
	sha1sum = models.CharField(max_length=40,unique=True)
	sha256sum = models.CharField(max_length=64,unique=True)
	package_name = models.CharField(max_length=200,null=True)
	dev_name = models.CharField(max_length=200,null=True)
	koodous_displayed_version = models.CharField(max_length=200,null=True)
	koodous = models.ForeignKey(koodous, on_delete=models.CASCADE,null=True)
	koodous_rating = models.IntegerField(null=True)
	virustotal = models.ForeignKey(virustotal, on_delete=models.CASCADE,null=True)
	vt_detected = models.IntegerField(null=True)
	vt_total = models.IntegerField(null=True)
	analysed = models.BooleanField(default=False)

	def __str__(self):
		return "%s , %s , %s , %s , %s , %s , %s , %s , %s , %s " % (self.md5sum  , self.sha1sum  , self.sha256sum  , self.package_name  , self.dev_name  , self.koodous  , self.koodous_rating  , self.virustotal  , self.vt_detected  , self.vt_total)

@python_2_unicode_compatible
class ipa(models.Model):
	md5sum = models.CharField(max_length=32,unique=True)
	sha1sum = models.CharField(max_length=40,unique=True)
	sha256sum = models.CharField(max_length=64,unique=True)
	dev_name = models.CharField(max_length=200)
	bundle_id = models.CharField(max_length=200)
	trackid = models.CharField(max_length=200)
	virustotal = models.ForeignKey(virustotal, on_delete=models.CASCADE,null=True)
	vt_rating = models.IntegerField(null=True)
	vt_total = models.IntegerField(null=True)

	def __str__(self):
		return "%s , %s , %s , %s , %s , %s , %s , %s , %s " % (self.md5sum  , self.sha1sum  , self.sha256sum  , self.dev_name  , self.bundle_id  , self.trackid  , self.virustotal  , self.vt_rating  , self.vt_total)
  
class vt_flat(models.Model):
    virustotal = models.ForeignKey(virustotal, on_delete=models.CASCADE,null=True)
    sha256sum = models.CharField(max_length=64,unique=True)
    
    ALYac_detected = models.NullBooleanField()
    ALYac_result = models.CharField(max_length=200, default=None, null=True)
    AVG_detected = models.NullBooleanField()
    AVG_result = models.CharField(max_length=200, default=None, null=True)
    AVware_detected = models.NullBooleanField()
    AVware_result = models.CharField(max_length=200, default=None, null=True)
    AdAware_detected = models.NullBooleanField()
    AdAware_result = models.CharField(max_length=200, default=None, null=True)
    AegisLab_detected = models.NullBooleanField()
    AegisLab_result = models.CharField(max_length=200, default=None, null=True)
    Agnitum_detected = models.NullBooleanField()
    Agnitum_result = models.CharField(max_length=200, default=None, null=True)
    AhnLabV3_detected = models.NullBooleanField()
    AhnLabV3_result = models.CharField(max_length=200, default=None, null=True)
    Alibaba_detected = models.NullBooleanField()
    Alibaba_result = models.CharField(max_length=200, default=None, null=True)
    AntiVir_detected = models.NullBooleanField()
    AntiVir_result = models.CharField(max_length=200, default=None, null=True)
    AntiyAVL_detected = models.NullBooleanField()
    AntiyAVL_result = models.CharField(max_length=200, default=None, null=True)
    Arcabit_detected = models.NullBooleanField()
    Arcabit_result = models.CharField(max_length=200, default=None, null=True)
    Avast_detected = models.NullBooleanField()
    Avast_result = models.CharField(max_length=200, default=None, null=True)
    Avira_detected = models.NullBooleanField()
    Avira_result = models.CharField(max_length=200, default=None, null=True)
    Baidu_detected = models.NullBooleanField()
    Baidu_result = models.CharField(max_length=200, default=None, null=True)
    BaiduInternational_detected = models.NullBooleanField()
    BaiduInternational_result = models.CharField(max_length=200, default=None, null=True)
    BitDefender_detected = models.NullBooleanField()
    BitDefender_result = models.CharField(max_length=200, default=None, null=True)
    Bkav_detected = models.NullBooleanField()
    Bkav_result = models.CharField(max_length=200, default=None, null=True)
    ByteHero_detected = models.NullBooleanField()
    ByteHero_result = models.CharField(max_length=200, default=None, null=True)
    CATQuickHeal_detected = models.NullBooleanField()
    CATQuickHeal_result = models.CharField(max_length=200, default=None, null=True)
    CMC_detected = models.NullBooleanField()
    CMC_result = models.CharField(max_length=200, default=None, null=True)
    ClamAV_detected = models.NullBooleanField()
    ClamAV_result = models.CharField(max_length=200, default=None, null=True)
    Commtouch_detected = models.NullBooleanField()
    Commtouch_result = models.CharField(max_length=200, default=None, null=True)
    Comodo_detected = models.NullBooleanField()
    Comodo_result = models.CharField(max_length=200, default=None, null=True)
    CrowdStrike_detected = models.NullBooleanField()
    CrowdStrike_result = models.CharField(max_length=200, default=None, null=True)
    Cyren_detected = models.NullBooleanField()
    Cyren_result = models.CharField(max_length=200, default=None, null=True)
    DrWeb_detected = models.NullBooleanField()
    DrWeb_result = models.CharField(max_length=200, default=None, null=True)
    ESETNOD32_detected = models.NullBooleanField()
    ESETNOD32_result = models.CharField(max_length=200, default=None, null=True)
    Emsisoft_detected = models.NullBooleanField()
    Emsisoft_result = models.CharField(max_length=200, default=None, null=True)
    FProt_detected = models.NullBooleanField()
    FProt_result = models.CharField(max_length=200, default=None, null=True)
    FSecure_detected = models.NullBooleanField()
    FSecure_result = models.CharField(max_length=200, default=None, null=True)
    Fortinet_detected = models.NullBooleanField()
    Fortinet_result = models.CharField(max_length=200, default=None, null=True)
    GData_detected = models.NullBooleanField()
    GData_result = models.CharField(max_length=200, default=None, null=True)
    Ikarus_detected = models.NullBooleanField()
    Ikarus_result = models.CharField(max_length=200, default=None, null=True)
    Invincea_detected = models.NullBooleanField()
    Invincea_result = models.CharField(max_length=200, default=None, null=True)
    Jiangmin_detected = models.NullBooleanField()
    Jiangmin_result = models.CharField(max_length=200, default=None, null=True)
    K7AntiVirus_detected = models.NullBooleanField()
    K7AntiVirus_result = models.CharField(max_length=200, default=None, null=True)
    K7GW_detected = models.NullBooleanField()
    K7GW_result = models.CharField(max_length=200, default=None, null=True)
    Kaspersky_detected = models.NullBooleanField()
    Kaspersky_result = models.CharField(max_length=200, default=None, null=True)
    Kingsoft_detected = models.NullBooleanField()
    Kingsoft_result = models.CharField(max_length=200, default=None, null=True)
    Malwarebytes_detected = models.NullBooleanField()
    Malwarebytes_result = models.CharField(max_length=200, default=None, null=True)
    McAfee_detected = models.NullBooleanField()
    McAfee_result = models.CharField(max_length=200, default=None, null=True)
    McAfeeGWEdition_detected = models.NullBooleanField()
    McAfeeGWEdition_result = models.CharField(max_length=200, default=None, null=True)
    MicroWorldeScan_detected = models.NullBooleanField()
    MicroWorldeScan_result = models.CharField(max_length=200, default=None, null=True)
    Microsoft_detected = models.NullBooleanField()
    Microsoft_result = models.CharField(max_length=200, default=None, null=True)
    NANOAntivirus_detected = models.NullBooleanField()
    NANOAntivirus_result = models.CharField(max_length=200, default=None, null=True)
    Norman_detected = models.NullBooleanField()
    Norman_result = models.CharField(max_length=200, default=None, null=True)
    PCTools_detected = models.NullBooleanField()
    PCTools_result = models.CharField(max_length=200, default=None, null=True)
    Panda_detected = models.NullBooleanField()
    Panda_result = models.CharField(max_length=200, default=None, null=True)
    Qihoo360_detected = models.NullBooleanField()
    Qihoo360_result = models.CharField(max_length=200, default=None, null=True)
    Rising_detected = models.NullBooleanField()
    Rising_result = models.CharField(max_length=200, default=None, null=True)
    SUPERAntiSpyware_detected = models.NullBooleanField()
    SUPERAntiSpyware_result = models.CharField(max_length=200, default=None, null=True)
    Sophos_detected = models.NullBooleanField()
    Sophos_result = models.CharField(max_length=200, default=None, null=True)
    Symantec_detected = models.NullBooleanField()
    Symantec_result = models.CharField(max_length=200, default=None, null=True)
    Tencent_detected = models.NullBooleanField()

threatIntelligence/mobileappanalysis/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from lib.vt_koodous import *
from models import *
from lib.hashlib import isValidHash
from lib.corelib import runHashAnalysis,runUrlAnalysis,checkExistingHashes
import threading

# Create your views here.
def index(request):

	response = {}
	if request.method =="GET":
		return render(request, 'mobileappanalysis/index.html', response)
	else:
			hashes = request.POST['hashes']
			urls = request.POST['urls']
			if not urls and not hashes:
				Error_Message="No Urls or hashes To Check"
				response.update({"error":Error_Message})
				return render(request, 'mobileappanalysis/index.html', response)
			if hashes:
				finalResults = checkExistingHashes(hashes)
				response.update({"virustotal":finalResults["existing"]})
				
				t = threading.Thread(target=runHashAnalysis,
                            args=(finalResults["toBeChecked"],))
				t.setDaemon(True)
				t.start()
	    
				'''
				if urls:
					runUrlAnalysis(urls)
					response.update({"virustotal":urls})	
				'''
	return render(request, 'mobileappanalysis/index.html', response)

threatIntelligence/mobileappanalysis/templates/mobileappanalysis/auto.html
{% load static %}
<html>
<head>
	<title>Auto-populate database</title>
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
</head>
<body>
	<center>
		<h1>
			Auto-populate database
		</h1>
		<div id="main">
			<form method="POST" action="{% url 'mobileappanalysis:auto' %}">
			{% csrf_token %}
                <p>Requests batches of 25 malware and 25 goodware from Koodous and runs them through the APK analyser.</p>
                <p>Enter number of batches to analyse:</p>
                <input type="number" name="n_batches" value="n_batches" min="1">
                <input type="submit" name="begin" value="Begin">
                {% if message %}
					<h3 colour="red">{{ message }}</h3>
				{% endif %}
			</form>
		</div>
	</center>
</body>
</html>

threatIntelligence/mobileappanalysis/templates/mobileappanalysis/index.html
{% load static %}
<html>
<head>
	<title>APK Analysis View</title>
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
</head>
<body>
	<center>
		<h1>
			APK Analysis View
		</h1>
		<div id="main">
			<form method="POST" action="{% url 'mobileappanalysis:index' %}">
			{% csrf_token %}
				<h2>By Hash</h2>
				<p>Please Insert a Hash or List of Hashes To Check</p>
				<textarea rows="4" cols="50" name="hashes"></textarea>
				<h2>By URL</h2>
				<p>Please Insert a URL or List of URLs To Check</p>
				<textarea rows="4" cols="50" name="urls"></textarea>
				<br>
				<input type="submit" name="submit" value="Check">
				{% if error %}
					<h3 colour="red">{{ error }}</h3>
				{% endif %}
			</form>
		</div>
	
	{% if virustotal or koodous %}
		<h2>Results</h2>
		{% if virustotal %}
			<div id="result1">
				<div>
					<h3>VirusTotal</h3>
					<div class="divTable">
						<div class="divHeaderRow">
							<div class="divHeaderCell">no.</div>
							<div class="divHeaderCell">Signature</div>
							<div class="divHeaderCell">PackageName</div>
							<div class="divHeaderCell">Developer Name</div>
							<div class="divHeaderCell">Koodous Rating</div>
							<div class="divHeaderCell">VirusTotal Rating</div>
							<!--
							<div class="divHeaderCell">URL List</div>
							-->
						</div>
						{% for entry in virustotal %}
						<div class="divRow">
							<div class="divCell">
								{{ forloop.counter }}
							</div>	
							<div class="divCell">
								{{ entry.md5sum }}
							</div>	
							<div class="divCell">
								{%if entry.package_name %}
									{{ entry.package_name }}
								{% else %}
									-
								{% endif %}
							</div>	
							<div class="divCell">
								{%if entry.dev_name %}
									{{ entry.dev_name }}
								{% else %}
									-
								{% endif %}
							</div>	
							<div class="divCell">
								{%if entry.koodous_rating or entry.koodous_rating == 0  %}
									{{ entry.koodous_rating }}
								{% else %}
									-
								{% endif %}
							</div>	
							<div class="divCell">
								{% if not entry.vt_detected == None and not entry.vt_total == None %}
									{% if entry.vt_detected == 0 %}
										0
									{% else %}
										{{ entry.vt_detected}}/{{entry.vt_total }}
									{% endif %}
								{% else %}
									-
								{% endif %}
							</div>
							<!--
							<div class="divCell">
								{%if entry.koodous_id %}
									{% for url in entry.koodous.json_analysis_detailed.androguard.urls %}
										{{ url }}
									{% endfor %}
								{% else %}
									-
								{% endif %}
							</div>	
							-->
    					</div>
    					{% endfor %}
						</div>
					</div>
				</div>
			</div>
		{% endif %}

		{% if koodous %}
			<div id="result2">
				<div>
					<h3>Koodous</h2>
					{{ koodous }}
				</div>
			</div>
		{% endif %}
	{% endif %}
		
	</center>
</body>
</html>