threatIntelligence/androguard/urls.py
from django.conf.urls import url
from . import views

app_name = 'androguard'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

threatIntelligence/threatIntelligence/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from mobileappanalysis import urls as mobileappanalysisURLS
from machineLearning import urls as machineLearningURLS
from vtkoodousscraper import urls as vtkoodousscraperURLS
from androguard import urls as androguardURLS
import views

urlpatterns = [
    url(r'^$', views.index, name='mainIndex'),
    url(r'^admin/', admin.site.urls),
    url(r'^apk/', include(mobileappanalysisURLS)),
    url(r'^ml/', include(machineLearningURLS)),   
    url(r'^scraper/', include(vtkoodousscraperURLS)),
    url(r'^androguard', include(androguardURLS))
]

threatIntelligence/vtkoodousscraper/urls.py
from django.conf.urls import url
from . import views

app_name = 'vtkoodousscraper'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

threatIntelligence/vtkoodousscraper/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class search_position(models.Model):
    params =  models.TextField()
    search_URL = models.TextField()
    
    def __str__(self):
        return "%s , %s " % (self.params , self.search_URL)

threatIntelligence/vtkoodousscraper/views.py
from django.shortcuts import render
from mobileappanalysis.models import apk
from lib.coreLib import start_koodous, start_virustotal, stop_koodous, stop_vt


# Create your views here.
def index(request):
    response = {}
    
    response.update({"vmal": apk.objects.filter(vt_detected__gte=5).count()})
    response.update({"vbenign": apk.objects.filter(vt_detected__lt=5).count()})
    response.update({"vnull": apk.objects.filter(vt_detected__exact=None).count()})
    
    kmal = apk.objects.filter(koodous_rating__lt=0).count()
    kbenign = apk.objects.filter(koodous_rating__gte=0).count()
    response.update({"kmal": kmal})
    response.update({"kbenign": kbenign})
    
    if request.method == "POST":
        if 'koodousbegin' in request.POST.keys():
            if kmal > kbenign:
                start_koodous('benign')
            else:
                start_koodous('malign')
        elif 'koodousstop' in request.POST.keys():
            stop_koodous()
        elif 'vtbegin' in request.POST.keys():
            start_virustotal()
        elif 'vtstop' in request.POST.keys():
            stop_vt()

    return render(request, 'vtkoodousscraper/index.html', response)

threatIntelligence/vtkoodousscraper/templates/vtkoodousscraper/index.html
{% load static %}
<html>
<head>
	<title>Auto-populate database</title>
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
</head>
<body>
	<center>
		<h1>
			Auto-populate database
		</h1>
      <h2>Status</h2>
      <p>Koodous: <b>{{ kmal }}</b> negatively rated apps, <b>{{ kbenign }}</b> unrated apps.</p>
      <p>Virustotal: <b>{{ vmal}}</b> malicious apps, <b>{{ vbenign }}</b> benign apps and <b>{{ vnull }}</b> unrated apps.</p>
		<div id="main">
			<form method="POST" action="{% url 'vtkoodousscraper:index' %}">
			{% csrf_token %}
                <h2>Auto-populate from Koodous</h2>
                <p>Begin collecting batches from Koodous. A batch consists of 25 negatively rated (malign) or 25 unrated (mostly benign) apps from Koodous.</p>
                <p>Auto-populater will attempt to equalise the number of malign and benign apps in the database.</p>
                <input type="submit" name="koodousbegin" value="Begin">
                <input type="submit" name="koodousstop" value="Stop">
			</form>
      <form method="POST" action="{% url 'vtkoodousscraper:index' %}">
			{% csrf_token %}
                <h2>Collect labels from Virustotal</h2>
                <p>Begin collecting labels from Virustotal for apps in database.</p>
                <input type="submit" name="vtbegin" value="Begin">
                <input type="submit" name="vtstop" value="Stop">
			</form>
		</div>
	</center>
</body>
</html>